In [1]:
print("Hello, World!")

Hello, World!

In [3]:
import pandas as pd

In [4]:
#kaggle datasets download -d benroshan/ecommerce-data
#Expand-Archive -Path ecommerce-data.zip -DestinationPath data
order_df = pd.read_csv("C:\\Users\\jeric\\OneDrive\\Desktop\\coding_Projects\\e_commerce\\data\\Order Details.csv")
list_df = pd.read_csv("C:\\Users\\jeric\\OneDrive\\Desktop\\coding_Projects\\e_commerce\\data\\List of Orders.csv")
sales_df = pd.read_csv("C:\\Users\\jeric\\OneDrive\\Desktop\\coding_Projects\\e_commerce\\data\\Sales target.csv")

In [5]:
order_df.head()

  Order ID  Amount  Profit  Quantity     Category      Sub-Category
0  B-25601  1275.0 -1148.0         7    Furniture         Bookcases
1  B-25601    66.0   -12.0         5     Clothing             Stole
2  B-25601     8.0    -2.0         3     Clothing       Hankerchief
3  B-25601    80.0   -56.0         4  Electronics  Electronic Games
4  B-25602   168.0  -111.0         2  Electronics            Phones

In [6]:
order_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   str
 1   Amount        1500 non-null   float64
 2   Profit        1500 non-null   float64
 3   Quantity      1500 non-null   int64
 4   Category      1500 non-null   str
 5   Sub-Category  1500 non-null   str
dtypes: float64(2), int64(1), str(3)
memory usage: 70.4 KB

In [7]:
order_df.describe()

            Amount       Profit     Quantity
count  1500.000000  1500.000000  1500.000000
mean    287.668000    15.970000     3.743333
std     461.050488   169.140565     2.184942
min       4.000000 -1981.000000     1.000000
25%      45.000000    -9.250000     2.000000
50%     118.000000     9.000000     3.000000
75%     322.000000    38.000000     5.000000
max    5729.000000  1698.000000    14.000000

In [8]:
#renaming columns to lowercase and replacing spaces with underscores
order_df.columns = order_df.columns.str.lower().str.replace(' ', '_')
order_df.rename(columns={'sub-category': 'sub_category'}, inplace=True)
order_df.head()

  order_id  amount  profit  quantity     category      sub_category
0  B-25601  1275.0 -1148.0         7    Furniture         Bookcases
1  B-25601    66.0   -12.0         5     Clothing             Stole
2  B-25601     8.0    -2.0         3     Clothing       Hankerchief
3  B-25601    80.0   -56.0         4  Electronics  Electronic Games
4  B-25602   168.0  -111.0         2  Electronics            Phones

In [9]:
#identifying missing values in the dataset
print(order_df.isnull().sum())

order_id        0
amount          0
profit          0
quantity        0
category        0
sub_category    0
dtype: int64

In [10]:
#removing rows with all missing values
order_df.dropna(how='all', inplace=True)
print(order_df.isnull().sum())

order_id        0
amount          0
profit          0
quantity        0
category        0
sub_category    0
dtype: int64

In [11]:
#identifying duplicate rows in the dataset
order_df.duplicated().sum()

np.int64(0)

In [12]:
#checking for negative values in the dataset
order_df[order_df['profit'] < 0]

     order_id  amount  profit  quantity     category      sub_category
0     B-25601  1275.0 -1148.0         7    Furniture         Bookcases
1     B-25601    66.0   -12.0         5     Clothing             Stole
2     B-25601     8.0    -2.0         3     Clothing       Hankerchief
3     B-25601    80.0   -56.0         4  Electronics  Electronic Games
4     B-25602   168.0  -111.0         2  Electronics            Phones
...       ...     ...     ...       ...          ...               ...
1465  B-26093    33.0    -1.0         1     Clothing             Saree
1479  B-26096   264.0   -26.0         3     Clothing          Trousers
1484  B-26097   185.0   -26.0         6    Furniture            Chairs
1485  B-26097   663.0  -212.0         5  Electronics          Printers
1486  B-26097   671.0  -309.0         5  Electronics  Electronic Games

[503 rows x 6 columns]

In [13]:
order_df[order_df['quantity'] < 0]

Empty DataFrame
Columns: [order_id, amount, profit, quantity, category, sub_category]
Index: []

In [14]:
order_df[order_df['amount'] < 0]

Empty DataFrame
Columns: [order_id, amount, profit, quantity, category, sub_category]
Index: []

In [15]:
#check how many unique orders have negative profit
order_df[order_df['profit'] < 0]['order_id'].nunique()

222

In [16]:
#identifying the categories with the highest negative profit
order_df[order_df['profit'] < 0].groupby('category')['profit'].sum().sort_values()

category
Electronics   -16722.0
Furniture     -15521.0
Clothing      -11993.0
Name: profit, dtype: float64

In [17]:
#flagging negative profit values in the dataset
order_df['is_negative_profit'] = order_df['profit'] < 0

In [18]:
list_df.head()

  Order ID  Order Date CustomerName           State       City
0  B-25601  01-04-2018       Bharat         Gujarat  Ahmedabad
1  B-25602  01-04-2018        Pearl     Maharashtra       Pune
2  B-25603  03-04-2018        Jahan  Madhya Pradesh     Bhopal
3  B-25604  03-04-2018       Divsha       Rajasthan     Jaipur
4  B-25605  05-04-2018      Kasheen     West Bengal    Kolkata

In [19]:
list_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      500 non-null    str
 1   Order Date    500 non-null    str
 2   CustomerName  500 non-null    str
 3   State         500 non-null    str
 4   City          500 non-null    str
dtypes: str(5)
memory usage: 22.0 KB

In [20]:
list_df.describe()

       Order ID  Order Date CustomerName           State    City
count       500         500          500             500     500
unique      500         307          332              19      24
top     B-25601  24-11-2018       Shreya  Madhya Pradesh  Indore
freq          1           7            6             101      76

In [21]:
#renaming columns to lowercase and replacing spaces with underscores
list_df.columns = list_df.columns.str.lower().str.replace(' ', '_')
list_df.rename(columns={'customername': 'customer_name'}, inplace=True)
list_df.head()

  order_id  order_date customer_name           state       city
0  B-25601  01-04-2018        Bharat         Gujarat  Ahmedabad
1  B-25602  01-04-2018         Pearl     Maharashtra       Pune
2  B-25603  03-04-2018         Jahan  Madhya Pradesh     Bhopal
3  B-25604  03-04-2018        Divsha       Rajasthan     Jaipur
4  B-25605  05-04-2018       Kasheen     West Bengal    Kolkata

In [22]:
#identifying missing values in the dataset
print(list_df.isnull().sum())

order_id         60
order_date       60
customer_name    60
state            60
city             60
dtype: int64

In [23]:
list_df[list_df.isnull().all(axis=1)]

    order_id order_date customer_name state city
500      NaN        NaN           NaN   NaN  NaN
501      NaN        NaN           NaN   NaN  NaN
502      NaN        NaN           NaN   NaN  NaN
503      NaN        NaN           NaN   NaN  NaN
504      NaN        NaN           NaN   NaN  NaN
505      NaN        NaN           NaN   NaN  NaN
506      NaN        NaN           NaN   NaN  NaN
507      NaN        NaN           NaN   NaN  NaN
508      NaN        NaN           NaN   NaN  NaN
509      NaN        NaN           NaN   NaN  NaN
510      NaN        NaN           NaN   NaN  NaN
511      NaN        NaN           NaN   NaN  NaN
512      NaN        NaN           NaN   NaN  NaN
513      NaN        NaN           NaN   NaN  NaN
514      NaN        NaN           NaN   NaN  NaN
515      NaN        NaN           NaN   NaN  NaN
516      NaN        NaN           NaN   NaN  NaN
517      NaN        NaN           NaN   NaN  NaN
518      NaN        NaN           NaN   NaN  NaN
519      NaN        NaN           NaN   NaN  NaN
520      NaN        NaN           NaN   NaN  NaN
521      NaN        NaN           NaN   NaN  NaN
522      NaN        NaN           NaN   NaN  NaN
523      NaN        NaN           NaN   NaN  NaN
524      NaN        NaN           NaN   NaN  NaN
525      NaN        NaN           NaN   NaN  NaN
526      NaN        NaN           NaN   NaN  NaN
527      NaN        NaN           NaN   NaN  NaN
528      NaN        NaN           NaN   NaN  NaN
529      NaN        NaN           NaN   NaN  NaN
530      NaN        NaN           NaN   NaN  NaN
531      NaN        NaN           NaN   NaN  NaN
532      NaN        NaN           NaN   NaN  NaN
533      NaN        NaN           NaN   NaN  NaN
534      NaN        NaN           NaN   NaN  NaN
535      NaN        NaN           NaN   NaN  NaN
536      NaN        NaN           NaN   NaN  NaN
537      NaN        NaN           NaN   NaN  NaN
538      NaN        NaN           NaN   NaN  NaN
539      NaN        NaN           NaN   NaN  NaN
540      NaN        NaN           NaN   NaN  NaN
541      NaN        NaN           NaN   NaN  NaN
542      NaN        NaN           NaN   NaN  NaN
543      NaN        NaN           NaN   NaN  NaN
544      NaN        NaN           NaN   NaN  NaN
545      NaN        NaN           NaN   NaN  NaN
546      NaN        NaN           NaN   NaN  NaN
547      NaN        NaN           NaN   NaN  NaN
548      NaN        NaN           NaN   NaN  NaN
549      NaN        NaN           NaN   NaN  NaN
550      NaN        NaN           NaN   NaN  NaN
551      NaN        NaN           NaN   NaN  NaN
552      NaN        NaN           NaN   NaN  NaN
553      NaN        NaN           NaN   NaN  NaN
554      NaN        NaN           NaN   NaN  NaN
555      NaN        NaN           NaN   NaN  NaN
556      NaN        NaN           NaN   NaN  NaN
557      NaN        NaN           NaN   NaN  NaN
558      NaN        NaN           NaN   NaN  NaN
559      NaN        NaN           NaN   NaN  NaN

In [24]:
#removing rows with all missing values
list_df.dropna(how='all', inplace=True)
print(list_df.isnull().sum())

order_id         0
order_date       0
customer_name    0
state            0
city             0
dtype: int64

In [25]:
#checking format of the order_date column
pd.to_datetime(list_df['order_date'], errors='coerce')

0     2018-01-04
1     2018-01-04
2     2018-03-04
3     2018-03-04
4     2018-05-04
         ...
495          NaT
496          NaT
497          NaT
498          NaT
499          NaT
Name: order_date, Length: 500, dtype: datetime64[us]

In [26]:
#reformatting the order_date column to datetime format using the correct format
list_df['order_date'] = pd.to_datetime(list_df['order_date'], format='%d-%m-%Y', errors='coerce')
pd.to_datetime(list_df['order_date'], errors='coerce')

0     2018-04-01
1     2018-04-01
2     2018-04-03
3     2018-04-03
4     2018-04-05
         ...
495   2019-03-28
496   2019-03-28
497   2019-03-29
498   2019-03-30
499   2019-03-31
Name: order_date, Length: 500, dtype: datetime64[us]

In [27]:
list_df['state'].unique()

<StringArray>
[          'Gujarat',       'Maharashtra',    'Madhya Pradesh',
         'Rajasthan',       'West Bengal',         'Karnataka',
 'Jammu and Kashmir',        'Tamil Nadu',     'Uttar Pradesh',
             'Bihar',           'Kerala ',            'Punjab',
           'Haryana',  'Himachal Pradesh',            'Sikkim',
               'Goa',          'Nagaland',    'Andhra Pradesh',
             'Delhi']
Length: 19, dtype: str

In [28]:
#identifying duplicate rows in the dataset
order_df.duplicated().sum()

np.int64(0)

In [29]:
sales_df.head(20)

   Month of Order Date   Category   Target
0               Apr-18  Furniture  10400.0
1               May-18  Furniture  10500.0
2               Jun-18  Furniture  10600.0
3               Jul-18  Furniture  10800.0
4               Aug-18  Furniture  10900.0
5               Sep-18  Furniture  11000.0
6               Oct-18  Furniture  11100.0
7               Nov-18  Furniture  11300.0
8               Dec-18  Furniture  11400.0
9               Jan-19  Furniture  11500.0
10              Feb-19  Furniture  11600.0
11              Mar-19  Furniture  11800.0
12              Apr-18   Clothing  12000.0
13              May-18   Clothing  12000.0
14              Jun-18   Clothing  12000.0
15              Jul-18   Clothing  14000.0
16              Aug-18   Clothing  14000.0
17              Sep-18   Clothing  14000.0
18              Oct-18   Clothing  16000.0
19              Nov-18   Clothing  16000.0

In [30]:
sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Month of Order Date  36 non-null     str
 1   Category             36 non-null     str
 2   Target               36 non-null     float64
dtypes: float64(1), str(2)
memory usage: 996.0 bytes

In [31]:
sales_df.describe()

             Target
count     36.000000
mean   12108.333333
std     2667.837541
min     9000.000000
25%    10050.000000
50%    11450.000000
75%    14500.000000
max    16000.000000

In [32]:
#renaming columns to lowercase and replacing spaces with underscores
sales_df.columns = sales_df.columns.str.lower().str.replace(' ', '_')
sales_df.head()

  month_of_order_date   category   target
0              Apr-18  Furniture  10400.0
1              May-18  Furniture  10500.0
2              Jun-18  Furniture  10600.0
3              Jul-18  Furniture  10800.0
4              Aug-18  Furniture  10900.0

In [33]:
#reformatting month of order date column to datetime format using the correct format
sales_df['month_of_order_date'] = pd.to_datetime(sales_df['month_of_order_date'], format='%b-%y', errors='coerce')
sales_df.head()

  month_of_order_date   category   target
0          2018-04-01  Furniture  10400.0
1          2018-05-01  Furniture  10500.0
2          2018-06-01  Furniture  10600.0
3          2018-07-01  Furniture  10800.0
4          2018-08-01  Furniture  10900.0

In [34]:
pd.to_datetime(list_df['order_date'], errors='coerce')

0     2018-04-01
1     2018-04-01
2     2018-04-03
3     2018-04-03
4     2018-04-05
         ...
495   2019-03-28
496   2019-03-28
497   2019-03-29
498   2019-03-30
499   2019-03-31
Name: order_date, Length: 500, dtype: datetime64[us]

In [35]:
#identifying missing values in the dataset
print(sales_df.isnull().sum())

month_of_order_date    0
category               0
target                 0
dtype: int64

In [36]:
#identifying duplicate rows in the dataset
sales_df.duplicated().sum()

np.int64(0)

In [37]:
sales_df[(sales_df['target'] < 0)]

Empty DataFrame
Columns: [month_of_order_date, category, target]
Index: []

In [38]:
#exporting the cleaned datasets to CSV files
order_df.to_csv("C:\\Users\\jeric\\OneDrive\\Desktop\\coding_Projects\\e_commerce\\cleaned_order_details.csv", index=False)
list_df.to_csv("C:\\Users\\jeric\\OneDrive\\Desktop\\coding_Projects\\e_commerce\\cleaned_list_of_orders.csv", index=False)
sales_df.to_csv("C:\\Users\\jeric\\OneDrive\\Desktop\\coding_Projects\\e_commerce\\cleaned_sales_target.csv", index=False)

In [ ]:
import sys
print(sys.executable)

c:\Users\jeric\OneDrive\Desktop\coding_Projects\e_commerce\myenv\Scripts\python.exe

In [51]:
from sqlalchemy import create_engine
import sys

engine = create_engine("postgresql://postgres:Matthew286@localhost:5432/postgres")

In [52]:
conn = engine.connect()
print("Connected!")

Connected!

In [53]:
#exporting the cleaned datasets to PostgreSQL database
order_df.to_sql('order_details', engine, if_exists='replace', index=False)
list_df.to_sql('orders', engine, if_exists='replace', index=False)
sales_df.to_sql('sales_target', engine, if_exists='replace', index=False)

36

In [55]:
sales_df.head()

  month_of_order_date   category   target
0          2018-04-01  Furniture  10400.0
1          2018-05-01  Furniture  10500.0
2          2018-06-01  Furniture  10600.0
3          2018-07-01  Furniture  10800.0
4          2018-08-01  Furniture  10900.0